### ISSUE TITLE
PHP error while adding product

### ISSUE THREAD

**Issue by Guenny0488** [fearless359/simpleinvoices#10]
Hi I get the following error while adding a / the first product. 
I have no idea why.
PHP log attached

![issue_1-13 01](https://cloud.githubusercontent.com/assets/18172313/21926308/818d6dd6-d981-11e6-82be-36cadf462b7c.PNG)
[php - Copy.zip](https://github.com/fearless359/simpleinvoices/files/704022/php.-.Copy.zip)

rgds

**Comment by fearless359** [comment]
The default for MySQL empty character string to numeric conversion is to make it a numeric zero. This is apparently not happening for you. It is possible that you need to update the version of your database or check to see if there is a rule that is stopping the automatic conversion. If a rule, remove it. If no rule and can't upgrade to current version, add a rule.

**Comment by Guenny0488** [comment]
Hi, i started from scratch with your latestet Version from GitHub and MySQL Community Server 5.7 this Weekend. As i thougth this issue Comes from a wrong config / steup of my System.

To understand what are you saying. 

MY Database Server has to handle the insert into of the empty value cost field to an 0 - right?

**Comment by fearless359** [comment]
Yes. I'm surprised it is an issue as this is the default functionality in the mySQL DBs I have deployed on two different systems.

**Comment by johnanastasio17** [comment]
I also had this problem too and wonder if it is a Wampserver issue. I setup everything on an Xampp localhost running PHP version: 7.1.1 and can now add products with no errors.

**Comment by fearless359** [comment]
Just uploaded changes that allow SI to run at 7.0x. I haven't tried 7.1x though.

**Comment by twobob** [comment]
current defaults (on windows at least appear to give)
**SELECT @@GLOBAL.sql_mode;
SELECT @@SESSION.sql_mode;**

> blah NO_ENGINE_SUBSTITUTION blah
`so sql_mode = '' `
in the my.ini fixes this issue
Hope it helps

**Comment by fearless359** [comment]
Personally, I haven't had issues with default installs of mySql packaged with xampp. But info might help someone.

**Comment by twobob** [comment]
Yes, this was for a full IIS, MySQL, PHP build from scratch job, perhaps that is the indeed the difference.
