### ISSUE TITLE
Is this safe to use as an upgrade over the official SI without needing to nuke the DB?

### ISSUE THREAD

**Issue by SoftwareGuy** [fearless359/simpleinvoices#11]
Hi there,

I came across this fork of Simple Invoices and it seems that it's had some TLC to make the system more secure and update Smarty and friends. I was wondering if I could do a in-place upgrade of this system over the official git version of Simple Invoices. I've already started customizing the official git version and some parts feel half baked or error on PHP 5.6.x or PHP 7 (namely the outdated PDF engine). I really don't want to have to nuke my database of 70 odd customers and products, etc.

Is this possible or will I have to press the big red button and nuke the database from orbit?

Cheers!

**Comment by ppmt** [comment]
First thing I would do is a backup of my database that's for sure. I would also copy the full directory of your current version of SI. Like that is something goes wrong you can easily go back to it.

Once you have down that do a fresh install of SI and then you can try to reimport your database.

**Comment by SoftwareGuy** [comment]
Okay, so I backed up the database and did what it said to "upgrade" over the older version of SimpleInvoices. Seems to have taken effect. I'll keep an eye out for any SQL query errors and if they pop up, I'll investigate further.

**Comment by fearless359** [comment]
Yes, the fearless359/simpleinvoices version will automatically upgrade your database when it is first run. All you should notice is a delay in the initial access. With changes merged today, my version now supports PHP 5.4x through PHP 5.6x using MySQL database. It does NOT support other DBMS at this time. It has been updated to use Smarty 3, which is a stepping-stone toward a goal of supporting PHP 7.
 
All for now and for Him,
Rich Rowley
(541)401-4778
rich@fearlesstechcomp.com
