### ISSUE TITLE
Total Style Invoice does not save total or description

### ISSUE THREAD

**Issue by johnanastasio17** [fearless359/simpleinvoices#19]
Creating "total" style invoice:
Invoice will save but does not record dollar amount of invoice (shows as $.00) and does not record text from item description. When it saves, it is saving itself as next invoice number (as it should).
Same behavior when viewing invoice directly in myphpadmin

Database server
    Server: 127.0.0.1 via TCP/IP
    Server type: MariaDB
    Server version: 10.1.21-MariaDB - mariadb.org binary distribution
    Protocol version: 10
    User: root@localhost
    Server charset: UTF-8 Unicode (utf8)

Web server
    Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.1
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 -
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 7.1.1

phpMyAdmin
    Version information: 4.6.5.2

**Comment by fearless359** [comment]
I can't upload the fix at this time, but if you make the changes to the three files shown in the attached images, you should be good to go.
![chg2](https://cloud.githubusercontent.com/assets/5422101/24838627/42c9e792-1d00-11e7-9e6c-9a302ee40a4d.jpg)
![chg3](https://cloud.githubusercontent.com/assets/5422101/24838626/42c9e21a-1d00-11e7-85a6-80fafa4be6ef.jpg)
![chg1](https://cloud.githubusercontent.com/assets/5422101/24838625/42c98806-1d00-11e7-90a8-71722e8d9187.jpg)

**Comment by johnanastasio17** [comment]
Thank You, above worked perfectly.
