### ISSUE TITLE
Export to pdf failure

### ISSUE THREAD

**Issue by johnanastasio17** [fearless359/simpleinvoices#23]
Export of any report or invoice to pdf throws the following:
Fatal error: Uncaught Error: Call to undefined function set_magic_quotes_runtime() in C:\xampp\htdocs\SI359\library\pdf\config.parse.php:153 Stack trace: #0 C:\xampp\htdocs\SI359\include\sql_queries.php(727): parse_config_file('./library/pdf/h...') #1 C:\xampp\htdocs\SI359\include\class\export.php(60): pdfThis('<html>\n<head>\n ...', 'Invoice_2421', true) #2 C:\xampp\htdocs\SI359\include\class\export.php(254): export->showData('<html>\n<head>\n ...') #3 C:\xampp\htdocs\SI359\modules\export\invoice.php(19): export->execute() #4 C:\xampp\htdocs\SI359\index.php(266): include('C:\\xampp\\htdocs...') #5 {main} thrown in C:\xampp\htdocs\SI359\library\pdf\config.parse.php on line 153

**Comment by fearless359** [comment]
This was fixed a bit ago so try loading a current copy of fearless359/simpleinvoices. Basically this function has long been deprecated (marked to removal from php) and in PHP 7, it was removed. So the fix I added tests that the function exists before executing it. Bottom line, it has been fixed.
