### ISSUE TITLE
Product copy to itemized Invoice

### ISSUE THREAD

**Issue by graeme86** [fearless359/simpleinvoices#24]
When selecting the Product on a Itemized Invoice the product notes are not being copied over to the invoice.

![simple1](https://cloud.githubusercontent.com/assets/2192991/25273941/fc578b24-265b-11e7-946f-172941721f12.jpg)
![simple2](https://cloud.githubusercontent.com/assets/2192991/25273940/fc56411a-265b-11e7-87b1-f9faf7ac66d7.jpg)

**Comment by fearless359** [comment]
Works on version 2018.2.5. Have you tried it there or a later version?
