### ISSUE TITLE
siLocal_number:'0' returns 2 decimal places.

### ISSUE THREAD

**Issue by twobob** [fearless359/simpleinvoices#27]
Hi.
I just noted that :'0' appears to be silently replaced by 2 decimal places.

![image](https://cloud.githubusercontent.com/assets/915232/26805183/b1acbabc-4a42-11e7-9f75-f1728383ba0d.png)

Here is is working as expected with :'1'
![image](https://cloud.githubusercontent.com/assets/915232/26805103/6f250da2-4a42-11e7-83eb-4c9ce8f0b522.png)

not a php guy. but thought I should report :)

**Comment by twobob** [comment]
I went with  siLocal_number_trim:'2' | myself as an alternate solution.

**Comment by fearless359** [comment]
The value is the decimal precision the number should be rounded to. Since this is a count field, it shouldn't have any decimal places.

**Comment by twobob** [comment]
indeed. and yet there are two.

**Comment by fearless359** [comment]
Looks like 0 means the same as 2. Tried a number of things. This is what I like best as it doesn't matter how many decimal places there are: siLocal_number_trim:"."

Not sure how this works with formats that don't use a period as the decimal place separator.

**Comment by twobob** [comment]
Thanks very much for your efforts.
I respect your dedication and knowledge. Noted, and appreciated on the shorthand.
