### ISSUE TITLE
Width of invoice entry stretched out/displaying improperly

### ISSUE THREAD

**Issue by johnanastasio17** [fearless359/simpleinvoices#29]
Not sure, what happened. Have made no changes to SI or it's underpinnings. When entering a new invoice, screen now appears like this:

![si-invoice-page](https://user-images.githubusercontent.com/26570098/37011935-424c94ee-20c0-11e8-9c4a-989ff98d1200.jpg)

Other pages and reports all seem to render properly.

**Comment by twobob** [comment]
Does pressing F12 and observing the console output show any obvious errors?
Always good for a dev to know.

**Comment by johnanastasio17** [comment]
Nothing in the console under any tabs. (Inspector, Console, Debugger, etc)

**Comment by twobob** [comment]
![image](https://user-images.githubusercontent.com/915232/37197621-5ff157e0-2373-11e8-97ea-46a561dec656.png)
Well. opened the console and had a bit of a look. Seems like the total width is constrained by the length of the content in the boxes.

Has someone added an item accidentally that is 2000 character long or something?
Either way you could constrain the box length actively via CSS at an absolute pinch. I have no idea what is wrong at your end but one could control that value by shoving a record for "#products0" in the stylesheet with a value of "width:500px !important" (if you find you really need the !important, try it without first)

![image](https://user-images.githubusercontent.com/915232/37197770-e2d96c4c-2373-11e8-9a05-79b90aa450c7.png)

Hope it helps at least be able to use your system while you figure it out.

**Comment by twobob** [comment]
Also I note that you have n<sup>10</sup> items in that list.  is that supposed to be like that?
No one else knows what you expect to see.  So clearly stating your expectations really helps.

"It's broken!" is not specific enough :)  

"IT'S BROKEN and I expected to see 2 items in my invoice template - HERE IS A PICTURE OF A WORKING ONE" is way more helpful.

**Comment by johnanastasio17** [comment]
_Has someone added an item accidentally that is 2000 character long or something?_
We have a winner! We did a "total" type invoice instead of an "itemized" invoice. This created an item that was a mile long which caused the behavior pictured above in the first post.
Thank you for giving us an idea on where to look, the problem is solved.

**Comment by fearless359** [comment]
I just uploaded changes that I believe will address this. The notes on the TOTAL_INVOICE get stored in the si_products table and the ID from that entry wasn't associating correctly with the invoice.

**Comment by twobob** [comment]
Score one for the crystal ball
