### ISSUE TITLE
mail forwarding mysteriously stopped working

### ISSUE THREAD

**Issue by twobob** [fearless359/simpleinvoices#35]
On a window box. The mail forwarding is just 500ing.

HTTP Error 500.0 - Internal Server Error
C:\Php7\php-cgi.exe - The FastCGI process exceeded configured activity timeout

It worked before. I checked for updated settings in the upstram mail and nothing had seemingly changed.
Clues on where to dig for the error?

Manay thanks

**Comment by fearless359** [comment]
This is probably a setup issue that has nothing to do with SI. You can google the error message and see a lot of comments about it. One of the most straight forward suggestions is to increase the setting of the activityTimeout for the FastCGI server.

**Comment by twobob** [comment]
Yeah I tried all that before polling up here. The "worked, now doesnt" thing precludes config errors.
Upstrem say no changes.  Hey ho, was asking about the internal logging - would that help me determine anything if enabled?

**Comment by fearless359** [comment]
If SI issue, first check the tmp/log/php.log file for errors. If you set zend.logger_level in custom.config.php to DEBUG, you will get a lot of logic flow information in the tmp/log/si.log file. Either of these can help you track down SI issues if issue is with SI.

**Comment by twobob** [comment]
That is excellent information. Thanks. doesn't point to a fail in SI. Just a note in php about Cannot Open
More likely an unknown change in the configuration/permissions on the machine somehow.
Appreciate the assist
