### ISSUE TITLE
New install on Ubuntu16.04/Apache2/PHP7

### ISSUE THREAD

**Issue by OutbackMatt** [fearless359/simpleinvoices#39]
Hi Rich,

Nice work!
After many years of using SI with some customisation on a Windows + IIS + PHP5.4 machine, I've decide to move it to my Ubuntu Apache2 PHP7 machine.

I copied my database over = easy
I created a zip from current state of your files, and unzipped them on my Ubuntu servre

Copied the custom.config.php over, and set the new username and password variables for the database.
When I start SI I get

Deprecated: Non-static method Log::open() should not be called statically in /var/www/html2/mattgilchrist/simpleinvoices/include/init.php on line 61

Fatal error: Uncaught Error: Call to undefined method Log::out() in /var/www/html/simpleinvoices/include/init.php:62 Stack trace: #0 /var/www/html/simpleinvoices/index.php(33): require_once() #1 {main} thrown in /var/www/html/simpleinvoices/include/init.php on line 62

I can't see any log lines created in any of the logs that I check. I am unsure if the database connection doesn't work, or something else is wrong...

Any ideas or hints?
Also the 'deprecated' error should be fixed I'd guess

**Comment by OutbackMatt** [comment]
An update
I found this version (your links on main page are broken) >> https://github.com/fearless359/simpleinvoices/archive/fearless359_v2018.1.2.zip
And that helped.

I had other issues though.
I couldn't log in until I updated the database, and the automatic database update wouldn't start until I had logged in. :/
I manually installed the SQL queries, one at a time, and it seems to be working better. There are still many issues, but I'll work though them.

There is a heap of depreciated errors (hundreds) when trying to send an email, and there are thousands of PHP Notices. I've had to block these just to get pages to load.

My Apache2/PHP7 is much faster for loading pages than my Windows 10/IIS/PHP5.4 was - thanks for work in cleaning up the SimpleInvoices code

My main plan is to only use TLS1.2 for SMTP connections, and I still had to modify the Zend Library to do that, even with the updated PHP and OpenSSL libraries.

Once I get SimpleInvoices running the way I like, then I'll add my custom mods back.
I'll look at doing a pull request from your repo.

Consider this issue closed.

**Comment by OutbackMatt** [comment]
When I go to update database using the wizard i get this error

Fatal error: Uncaught PdoDbException: [0]: PdoDb rollback(): Called when no transaction is in process. thrown in /var/www/html/simpleinvoices/include/class/PdoDb.php on line 863

**Comment by fearless359** [comment]
Make sure you are up to date with the latest version 2018.2.5. The error you are report have been corrected.

**Comment by OutbackMatt** [comment]
Where do I get that version?
Is that latest Master?

I have tried that, but I have a heap of issues with the new log function and I need to comment out all Log::out lines, plus the initial Log instantiator. I figured that was still a work in progress
