### ISSUE TITLE
api-cron not working well

### ISSUE THREAD

**Issue by vvcares** [fearless359/simpleinvoices#4]
No invoices recurred for this Cron run for domain: for the date: 2016-12-15.
Im sure, i have created the recurrence invoice.

![image](https://cloud.githubusercontent.com/assets/6436676/21222747/6be277ea-c2fe-11e6-9bdc-e33c36011ff3.png)

**Comment by fearless359** [comment]
This is a work in process. The CRON process fails if the terminal (aka batch) environment it runs in is set up  properly. I'm making changes to try and make it work without the environment set up other than what is needed to run the online interface. Will update all when a fix is available.

**Comment by fearless359** [comment]
Recent changes help cron to work. Possible that there is still an issue with the logo not showing on the invoice generated for the email's sent. So this remains a work in process to resolve that last issue.
