### ISSUE TITLE
pdf print = fatal error

### ISSUE THREAD

**Issue by Arvidas** [fearless359/simpleinvoices#61]
Google CP, Debian 4.9, PHP 7.0 

Any  export results in:

Fatal error: Uncaught TypeError: Return value of Inc\Claz\Export::setFormat() must be an instance of Inc\Claz\void, none returned in /var/www/simpleinvoices/Inc/Claz/Export.php:502 
Stack trace: 
- #0 /var/www/simpleinvoices/modules/export/invoice.php(20): Inc\Claz\Export->setFormat('print')
- #1 /var/www/simpleinvoices/index.php(374): include('/var/www/simple...') 
- #2 {main} thrown in /var/www/simpleinvoices/Inc/Claz/Export.php on line 502

**Comment by fearless359** [comment]
Can you upgrade to php 7.1 or higher? Turns out the return type of void support was not included in 7.0 but was in 7.1.  The other option is to remove the return type from this and all functions that have a void return type. Not a small change.

**Comment by Arvidas** [comment]
Thank you, it solved my issue!

After upgrade to 7.1 I got "Nothing to export message" and from logs
I saw missing "my custom" template.

**Comment by fearless359** [comment]
I can't find the message text, "Nothing to export" in the code. However, the message suggests that you have custom invoice template folder defined in the "SI Defaults" settings for "Default Invoice Template". Otherwise, I'm at a loss to know where this error originates.

**Comment by Arvidas** [comment]
As i said it's solved. Now do some work on that template.

I still need some work to do on sending email. 
There is error "One or more required fields is missing" after send email.
Possible some fields are not correctly imported from previous version of my database.
Thank you anyway, I let you know if I find something!
