### ISSUE TITLE
SQL Query details required for Invoices same as Invoices home page

### ISSUE THREAD

**Issue by rajyaguru01** [fearless359/simpleinvoices#65]
Hi,

I would like to get all the invoices datea generated using SQL query exactly same way as it is listed of  Invoice Homepage ? Sample columns I listed below. I understand it can be copied with page by page but if 20 pages listed , I needed action for 20 times. Rather I would prefer to use using SQL query, so I can export records in CSV files

Key Columns would required Invoice ID,Biller,Customer,Date,Total InvoicemOwing and Aging details

Could anyone help to get the SQL query for the same?  So I can get easily all the records using phpmyadmin ?

 ID | Biller | Customer | Date | Total | Owing | Aging
-- | -- | -- | -- | -- | -- | -- | --

Thank you.

**Comment by fearless359** [comment]
Submit on Simpleinvoices.group forsum.
