### ISSUE TITLE
Upgrading from very old version

### ISSUE THREAD

**Issue by malcolmfowler** [fearless359/simpleinvoices#66]
Hi,

Just moving from an old version of simpleinvoices and I'm getting this error when running the DB upgrade 

Fatal error: Uncaught PdoDbException: [0]: PdoDb rollback(): Called when no transaction is in process. thrown in E:\xampp\htdocs\simpleinvoices-master\include\class\PdoDb.php on line 891

I've shown previous patches and those that need applying below.

Thanks
Malcolm

SQL patch 265, Product - expand/show line item description has already been applied in release 20130314
SQL patch 266, Product - expand/show line item description has already been applied in release 20130322
SQL patch 267, Product Matrix - insert attribute types has already been applied in release 20130325
SQL patch 268, Product Matrix - insert attribute types has already been applied in release 20130327
SQL patch 269, Product Matrix - insert attribute types has already been applied in release 20130327
SQL patch 270, Make SimpleInvoices faster - add index has already been applied in release 20100419
SQL patch 271, Make SimpleInvoices faster - add index has already been applied in release 20100419
SQL patch 272, Add product attributes system preference has already been applied in release 20130313
SQL patch 273, Make SimpleInvoices faster - add index has already been applied in release 20130927
SQL patch 274, Only One Default Variable name per domain allowed - add unique index has already been applied in release 20131007
SQL patch 275, Make EMail / Password pair unique per domain - add unique index has already been applied in release 20131007
SQL patch 276, Each invoice Item must belong to a specific Invoice with a specific domain_id has already been applied in release 20131008
SQL patch 277, Add Index for Quick Invoice Item Search for a domain_id has already been applied in release 20131008
SQL patch 278, Each Invoice Item can have only one instance of each tax has already been applied in release 20131008
SQL patch 279, Drop unused superceeded table si_product_matrix if present has already been applied in release 20131009
SQL patch 280, Each domain has their own extension instances has already been applied in release 20131011
SQL patch 281, Each domain has their own custom_field id sets has already been applied in release 20131011
SQL patch 282, Each domain has their own logs has already been applied in release 20131011
SQL patch 283, Match field type with foreign key field si_user.id has already been applied in release 20131012
SQL patch 284, Make si_index sub_node and sub_node_2 fields as integer has already been applied in release 20131016
SQL patch 285, Fix compound Primary Key for si_index table has already been applied in release 20131016
SQL patch 286, Speedup lookups from si_index table with indices in si_invoices table has not been applied to the database
SQL patch 287, Populate additional user roles like domain_administrator has not been applied to the database
SQL patch 288, Fully relational now - do away with the si_index table has not been applied to the database
SQL patch 289, Each cron_id can run a maximum of only once a day for each domain_id has not been applied to the database
SQL patch 290, Set all Flag fields to tinyint(1) and other 1 byte fields to char has not been applied to the database
SQL patch 291, Clipped size of zip_code and credit_card_number fields to realistic values has not been applied to the database
SQL patch 292, Added Customer/Biller User ID column to user table has not been applied to the database
SQL patch 293, Add department to the customers has not been applied to the database
SQL patch 294, Add custom_flags table for products. has not been applied to the database
SQL patch 295, Add net income report. has not been applied to the database
SQL patch 296, Add past due report. has not been applied to the database
SQL patch 297, Add User Security enhancement fields and values has not been applied to the database
SQL patch 298, Add Signature field to the biller table. has not been applied to the database
SQL patch 299, Add check number field to the payment table. has not been applied to the database
SQL patch 300, Add install complete table. has not been applied to the database
SQL patch 301, Add last_activity_date, aging_date and aging_value to invoices. has not been applied to the database
SQL patch 302, Added owing to invoices table has not been applied to the database
SQL patch 303, Add invoice custom field report extension to standard application and add sales_representative field. has not been applied to the database
SQL patch 304, Add default_invoice field to the customers table. has not been applied to the database
SQL patch 305, Add expense tables to the database. has not been applied to the database

**Comment by fearless359** [comment]
Please join the simpleinvoices.group forum and report your issue there. Also, zip your php.log file and append it to you message on this forum.

 

All for now and for Him,

Rich Rowley

**Comment by fearless359** [comment]
Handled on Simpleinvoices.group.
