### ISSUE TITLE
Slow response times

### ISSUE THREAD

**Issue by malcolmfowler** [fearless359/simpleinvoices#79]
I think I may have simpleinvoices installed incorrectly and I'm seeking some advice.  The system is loaded on my dev server which has typical response times for the web apps I develop. i.e. sub-second.  
When I access simpleinvoices here are some typical timings
Open index.php - 15 seconds
Open Invoices screen - 5 seconds, them another 10 seconds to show the invoice grid.
New invoice button - 5 seconds to display blank invoice.

These sort of timings are the same across the system.  I have about 100 invoices on the system.

Any guidance appreciated.
Thanks
Malcolm

**Comment by fearless359** [comment]
Please post this on the simpleinvoices.group forum.
