### ISSUE TITLE
Remove labels from invoice template

### ISSUE THREAD

**Issue by donttrustem** [fearless359/simpleinvoices#8]
Hi, I am using the latest version of simple invoice but having problems trying to remove the labels from the invoice template.

Thanks
Mark

**Comment by fearless359** [comment]
Here is a link to info on changing templates and possibly some example templates you can use. To modify templates, you should know smarty and php coding. If you have specific labels to change in the standard template, I can see what it involves. However the scope of changing templates is beyond the primary support I provide for this thread. Here is a link to check out: https://github.com/simpleinvoices/simpleinvoices/wiki/InvoiceTemplates
