### ISSUE TITLE
Getting blank page and nothing in apache's errors.log

### ISSUE THREAD

**Issue by webcoder-eu** [fearless359/simpleinvoices#81]
Hi,

I'm on Ubuntu 20.04 LTS and am trying to move SI from my Centos into this new instance. I've used both code bases 2019 and 2020. Unfortunately, after solving some config/custom.config.php.new and permissions problems, am getting a blank page when accessing SI and no errors are produced.

I'm on:
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2020-08-12T19:46:17
PHP 8.0.2
MySQL Server version: 8.0.23-0ubuntu0.20.04.1 (Ubuntu).

All neccessary modules installed and no complaints in the apache's error log file.

Many thanks in advance
David

**Comment by webcoder-eu** [comment]
Ok, I see the problem

`$ composer update

Deprecation Notice: Required parameter $path follows optional parameter $schema in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Required parameter $path follows optional parameter $schema in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:108
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:130
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:130
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit 7.5.9 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.8 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.7 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.6 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.5 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.4 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.3 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.20 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.2 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.19 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.18 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.17 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.16 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.15 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.14 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.13 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.12 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.11 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.10 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.1 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.0 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.4.5 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.4.4 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.4.3 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.4.2 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.4.1 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.4.0 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.3.5 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.3.4 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.3.3 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.3.2 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.3.1 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.3.0 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.2.7 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.2.6 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.2.5 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.2.4 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.2.3 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.2.2 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.2.1 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.2.0 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.1.5 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.1.4 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.1.3 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.1.2 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.1.1 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.1.0 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.0.3 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.0.2 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.0.1 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.0.0 requires php ^7.1 -> your PHP version (8.0.2) does not satisfy that requirement.
    - phpunit/phpunit 7.5.20 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - Installation request for phpunit/phpunit ^7 -> satisfiable by phpunit/phpunit[7.0.0, 7.0.1, 7.0.2, 7.0.3, 7.1.0, 7.1.1, 7.1.2, 7.1.3, 7.1.4, 7.1.5, 7.2.0, 7.2.1, 7.2.2, 7.2.3, 7.2.4, 7.2.5, 7.2.6, 7.2.7, 7.3.0, 7.3.1, 7.3.2, 7.3.3, 7.3.4, 7.3.5, 7.4.0, 7.4.1, 7.4.2, 7.4.3, 7.4.4, 7.4.5, 7.5.0, 7.5.1, 7.5.10, 7.5.11, 7.5.12, 7.5.13, 7.5.14, 7.5.15, 7.5.16, 7.5.17, 7.5.18, 7.5.19, 7.5.2, 7.5.20, 7.5.3, 7.5.4, 7.5.5, 7.5.6, 7.5.7, 7.5.8, 7.5.9].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/8.0/cli/php.ini
    - /etc/php/8.0/cli/conf.d/10-mysqlnd.ini
    - /etc/php/8.0/cli/conf.d/10-opcache.ini
    - /etc/php/8.0/cli/conf.d/10-pdo.ini
    - /etc/php/8.0/cli/conf.d/20-bz2.ini
    - /etc/php/8.0/cli/conf.d/20-calendar.ini
    - /etc/php/8.0/cli/conf.d/20-ctype.ini
    - /etc/php/8.0/cli/conf.d/20-curl.ini
    - /etc/php/8.0/cli/conf.d/20-exif.ini
    - /etc/php/8.0/cli/conf.d/20-ffi.ini
    - /etc/php/8.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/8.0/cli/conf.d/20-ftp.ini
    - /etc/php/8.0/cli/conf.d/20-gd.ini
    - /etc/php/8.0/cli/conf.d/20-gettext.ini
    - /etc/php/8.0/cli/conf.d/20-iconv.ini
    - /etc/php/8.0/cli/conf.d/20-intl.ini
    - /etc/php/8.0/cli/conf.d/20-mbstring.ini
    - /etc/php/8.0/cli/conf.d/20-mysqli.ini
    - /etc/php/8.0/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/8.0/cli/conf.d/20-phar.ini
    - /etc/php/8.0/cli/conf.d/20-posix.ini
    - /etc/php/8.0/cli/conf.d/20-readline.ini
    - /etc/php/8.0/cli/conf.d/20-shmop.ini
    - /etc/php/8.0/cli/conf.d/20-sockets.ini
    - /etc/php/8.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/8.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/8.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/8.0/cli/conf.d/20-tokenizer.ini
    - /etc/php/8.0/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.`

**Comment by redcuillin** [comment]
I think the short answer is that SI doesn't support PHP 8+ yet. Given that it wasn't that long ago that it still didn't work with PHP 7, it's understandable, and 8 is still kind of 'bleeding edge' in many contexts. You're almost inevitably going to run into a lot of code that won't work with it in some very mainstream applications.

The easiest solution would be to downgrade to PHP 7.4. There's a good chance it's already installed on your machine, and you just need to change the version of PHP that your server is using (eg if you use Apache, 'sudo a2dismod php8.0' followed by 'sudo a2enmod php7.4' and then 'sudo service apache2 restart'). Since Ubuntu 20.04 doesn't provide PHP 8, I'm guessing you probably installed it via the Ondřej Surý PPA Repository. It's been very useful over the years, but I know it will automatically activate PHP 8, which is not ideal at the moment. Maybe in 6 months.

Re all the composer errors:

If you're just downloading to use SI and not to provide code changes, just install from the Zip (not git clone). I wouldn't think there's any need for you to run composer update, or even composer install. The download includes everything you need to run SI under PHP 7.4 already. In effect, 'composer install' has been run for you. If you really want the latest composer code, then run 'composer install --no-dev' to avoid installing PHPunit and triggering all those errors.

If you are not getting a 500 error in your browser, I'd suggest the lack of errors is probably that error_reporting is switched off in the php.ini file for PHP 8's apache module. Enabling error reporting will reveal where the problems are in PHP 8, if you actually want to try to make it work.

**Comment by fearless359** [comment]
If you are installing fresh, use the 2020_master with PHP 7.4. If you are upgrading, you first need to load and run master_2019.2 so that required database update, foreign keys in particular, are applied. Then move to master_2020. This information is available to you on the simpleinvoices.group forum. The forum is also the best way to report issues, etc.

**Comment by webcoder-eu** [comment]
Hi,

Thank you for you patience, helpful answers and not calling me an idiot :) 

I've not touched this stuff for a couple of years now and it was my mistake. As soon as composer was run the problem was obvious i.e. a compatibility issue with PHP 8.0.
There are two ways of resolving it namely downgrading my PHP to supported version 7.4 or updating this code to make it compatible.

One thing I'm wondering about is database compatibility between all three versions? Has there been any significant changes (a simple yes/no will do before I dive in and do schemas comparision) and how keen are you, apart from making this app compatible with latest linux packages, on merging new features e.g. have added to my old SI an invoice number prefix that's set on each client?
I got mine from https://github.com/simpleinvoices2/simpleinvoices which was made compatible with PHP 5.6.40 and am trying to assess work required to migrate over exisitng data.

Cheers,
David

**Comment by redcuillin** [comment]
Hi David - I think @fearless359 has already answered your question. To get upgraded from the old version, install and run master_2019.2 to get your database upgraded properly, then upgrade to master_2020. However, as he also said, these sorts of support questions (and suggestions) are best asked at https://simpleinvoices.group/. Good luck!
