### ISSUE TITLE
Setting / SI defaults / Fatal error

### ISSUE THREAD

**Issue by groucha17** [fearless359/simpleinvoices#82]
Hello,
I am used to create invoices with 2011 version and as I have updated the server to php 7.4, nothing works anymore. I have updated si to master 2020. As I want to configure default settings I have an error when I click on the button.

Fatal error: Uncaught TypeError: Return value of Inc\Claz\SystemDefaults::getDelete() must be of the type int, string returned in /home/clients/ea27f7cbee09d7101a32496af37c62cf/web/facturier2020/Inc/Claz/SystemDefaults.php:216 Stack trace: #0 /home/clients/ea27f7cbee09d7101a32496af37c62cf/web/facturier2020/modules/system_defaults/manage.php(28): Inc\Claz\SystemDefaults::getDelete() #1 /home/clients/ea27f7cbee09d7101a32496af37c62cf/web/facturier2020/index.php(440): include('/home/clients/e...') #2 {main} thrown in /home/clients/ea27f7cbee09d7101a32496af37c62cf/web/facturier2020/Inc/Claz/SystemDefaults.php on line 216

What should I do please to set it up ?

Can I upload my datas from my 2011 version to the master 2020 tables ?

Regards

Stéphane

**Comment by rborcherds** [comment]
You will need to edit the System_Defaults table in the database.  Look for the DELETE and change it from an N or Y to 0 for no or 1 for yes.
