### ISSUE TITLE
UTF8 characters break product descriptions/dropdowns

### ISSUE THREAD

**Issue by redcuillin** [fearless359/simpleinvoices#83]
After upgrading to master_2019.2 some products wouldn't display in the new product page.

On directly editing the MySQL si_products.description field, it turned out that the problem was caused by the presence of a UTF-8 m-dash character (–) in product names. Changing them to a standard hyphen resolved the problem.

I'll try to work out a patch if I can, but it may be something connected to database character encoding or collation that's beyond me to working out quickly. The database was upgraded from a version that would have been MyISAM and non UTF-8 in the past and is now INNODB/UTF-8.

**Comment by fearless359** [comment]
The conversion from MyISAM to INNODB/UTF-8 shouldn't alter data in the database. This is the first reporting of such an incident and it appears that you have remedied your issue. Note that reporting of issues should be done through the SimpleInvoice.group knowledgebase. So if you encounter some question or issue in the future, please report it there. That way, all subscribers can view and see resolution.
